### ISSUE TITLE
Error adding unregistered packages

### ISSUE THREAD

**Issue by pdeffebach** [JuliaLang/Pkg.jl#1098]
```
(PackagesPrecompile) pkg> add https://github.com/mkborregaard/VerySimpleRasters.jl
   Cloning git-repo `https://github.com/mkborregaard/VerySimpleRasters.jl`
  Updating git-repo `https://github.com/mkborregaard/VerySimpleRasters.jl`
 Resolving package versions...
  Updating `~/.julia/packages/PackageCompiler/SGFCk/packages/Project.toml`
  [15e4465c] + VerySimpleRasters v0.1.0 #master (https://github.com/mkborregaard/VerySimpleRasters.jl)
  Updating `~/.julia/packages/PackageCompiler/SGFCk/packages/Manifest.toml`
  [a74b3585] + Blosc v0.5.1
  [f67ccb44] + HDF5 v0.11.0
  [15e4465c] + VerySimpleRasters v0.1.0 #master (https://github.com/mkborregaard/VerySimpleRasters.jl)
  [8bf52ea8] + CRC32c

(PackagesPrecompile) pkg> dev VerySimpleRasters
ERROR: The following package names could not be resolved:
 * VerySimpleRasters (15e4465c-140a-11e9-1a09-6f7eeac38b3b in manifest but not in project)
Please specify by known `name=uuid`.
```

`add`ing and then `dev`ing an unregistered package causes problems for me. Is this an expected error? Or is something going wrong?

**Comment by asinghvi17** [comment]
Just chiming in here - I've had the same issue.  However, the package entry exists in both `Project.toml` and `Manifest.toml`. 

In `Project.toml`:

```toml
VerySimpleRasters = "15e4465c-140a-11e9-1a09-6f7eeac38b3b"
```

In `Manifest.toml`:
```toml
[[VerySimpleRasters]]
deps = ["Dates", "HDF5", "Mmap", "RecipesBase"]
git-tree-sha1 = "ef2e34e1955bd3c4351fce4159109a53cd0106dc"
repo-rev = "master"
repo-url = "https://github.com/mkborregaard/VerySimpleRasters.jl"
uuid = "15e4465c-140a-11e9-1a09-6f7eeac38b3b"
version = "0.1.0"
```
