### ISSUE TITLE
`Instantiate -m` doesn't perform as described

### ISSUE THREAD

**Issue by jd-lara** [JuliaLang/Pkg.jl#1165]
I have an environment with a `Project.TOML` and `Manifest.TOML` where a package (in this Example SCS) is in the `Project.TOML` is as follows: 

```TOML
name = "test_pkg"
uuid = "46dbcece-61fa-11e9-262e-a3753fda25ea"
authors = ["Jose Daniel Lara <jdlara@berkeley.edu>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[extras]
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SCS"]
``` 
 In the Manifest,TOML, I specified that I want to use the master branch of SCS as follows: 

```TOML
[[SCS]]
deps = ["BinaryProvider", "Compat", "Libdl", "MathOptInterface", "MathProgBase"]
git-tree-sha1 = "f1a7eb2b02d5375df6e012a9da2c5ff57a55a6d6"
repo-rev = "master"
repo-url = "https://github.com/JuliaOpt/SCS.jl.git"
uuid = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
version = "0.5.1+"
```

When I check the `Manifest.TOML`, SCS shows as uninstalled, which is the desired behavior since this dependency is only for testing.

```Julia
(test_pkg) pkg> st -m
Project test_pkg v0.1.0
    Status `~/Dropbox/Code/test_codes/pkg/test_pkg/Manifest.toml`
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.3
  [49dc2e85] Calculus v0.4.1
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.1.0
  [864edb3b] DataStructures v0.15.0
  [163ba53b] DiffResults v0.0.4
  [b552c78f] DiffRules v0.0.10
  [f6369f11] ForwardDiff v0.10.3
  [4076af6c] JuMP v0.19.0
  [b8f27783] MathOptInterface v0.8.4
  [fdba3010] MathProgBase v0.7.7
  [77ba4419] NaNMath v0.3.2
  [bac558e1] OrderedCollections v1.1.0
→ [c946c3f1] SCS v0.5.1+ #master (https://github.com/JuliaOpt/SCS.jl.git)
  [276daf66] SpecialFunctions v0.7.2
  [90137ffa] StaticArrays v0.10.3
  [30578b45] URIParser v0.4.0
  [2a0f44e3] Base64 
  [ade2ca70] Dates 
  [8bb1440f] DelimitedFiles 
  [8ba89e20] Distributed 
  [b77e0a4c] InteractiveUtils 
  [76f85450] LibGit2 
  [8f399da3] Libdl 
  [37e2e46d] LinearAlgebra 
  [56ddb016] Logging 
  [d6f4376e] Markdown 
  [a63ad114] Mmap 
  [44cfe95a] Pkg 
  [de0858da] Printf 
  [3fa0cd96] REPL 
  [9a3f8284] Random 
  [ea8e919c] SHA 
  [9e88b42a] Serialization 
  [1a1011a3] SharedArrays 
  [6462fe0b] Sockets 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [8dfed614] Test 
  [cf7118a7] UUIDs 
  [4ec0a83e] Unicode 
┌ Warning: Some packages (indicated with a red arrow) are not downloaded, use `instantiate` to instantiate the current environment
└ @ Pkg.Display /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Display.jl:220
```

In the documentation says about instantiate "Download all the dependencies for the current project at the version given by the project's manifest." So, I added an instantiate call before running my tests to avoid issues with missing packages as follows:

```Bash
script:
  - julia --project --color=yes -e "import Pkg; Pkg.build(); Pkg.instantiate()"
  - julia --check-bounds=yes --depwarn=no --inline=no --color=yes --project -e "import Pkg; Pkg.test(coverage=true);"
```

Yet, I still get a missing package error when running tests in the CI. 

I went into the REPL to try to manually instantiate the `Manifest.TOML` replicating the conditions of the CI, and found out that the instantiate ignores the uninstalled package, see the example: 

```Julia
(test_pkg) pkg> instantiate
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
```

And it doesn't download the missing package. When checking the status of the Manifest still says uninstalled. 

```Julia
(test_pkg) pkg> st -m
Project test_pkg v0.1.0
    Status `~/Dropbox/Code/test_codes/pkg/test_pkg/Manifest.toml`
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.3
  [49dc2e85] Calculus v0.4.1
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.1.0
  [864edb3b] DataStructures v0.15.0
  [163ba53b] DiffResults v0.0.4
  [b552c78f] DiffRules v0.0.10
  [f6369f11] ForwardDiff v0.10.3
  [4076af6c] JuMP v0.19.0
  [b8f27783] MathOptInterface v0.8.4
  [fdba3010] MathProgBase v0.7.7
  [77ba4419] NaNMath v0.3.2
  [bac558e1] OrderedCollections v1.1.0
→ [c946c3f1] SCS v0.5.1+ #master (https://github.com/JuliaOpt/SCS.jl.git)
  [276daf66] SpecialFunctions v0.7.2
  [90137ffa] StaticArrays v0.10.3
  [30578b45] URIParser v0.4.0
  [2a0f44e3] Base64 
  [ade2ca70] Dates 
  [8bb1440f] DelimitedFiles 
  [8ba89e20] Distributed 
  [b77e0a4c] InteractiveUtils 
  [76f85450] LibGit2 
  [8f399da3] Libdl 
  [37e2e46d] LinearAlgebra 
  [56ddb016] Logging 
  [d6f4376e] Markdown 
  [a63ad114] Mmap 
  [44cfe95a] Pkg 
  [de0858da] Printf 
  [3fa0cd96] REPL 
  [9a3f8284] Random 
  [ea8e919c] SHA 
  [9e88b42a] Serialization 
  [1a1011a3] SharedArrays 
  [6462fe0b] Sockets 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [8dfed614] Test 
  [cf7118a7] UUIDs 
  [4ec0a83e] Unicode 
┌ Warning: Some packages (indicated with a red arrow) are not downloaded, use `instantiate` to instantiate the current environment
└ @ Pkg.Display /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Display.jl:220
```
