### ISSUE TITLE
Different package version being used than specified in Project.toml

### ISSUE THREAD

**Issue by blakeriley** [JuliaLang/Pkg.jl#1225]
I'm working on a package where I included CmdStan.jl as a dependency with v5.0.3 and StanDataFrames at v4.0.1. A colleague tried to use my package and got an error like:
```
ERROR: MethodError: no method matching convert_a3d(::Array{Float64,3}, ::Array{String,1}, ::Val{:dataframe}; start=101)
Closest candidates are:
  convert_a3d(::Any, ::Any, ::Val{:dataframe}) at C:\Users\blake.riley\.julia\packages\StanDataFrames\Qusdj\src\utilities\convert_a3d.jl:42 got unsupported keyword argument "start"
  convert_a3d(::Any, ::Any, ::Val{:array}; start) at C:\Users\blake.riley\.julia\packages\CmdStan\t3xOP\src\utilities\convert_a3d.jl:48
  convert_a3d(::Any, ::Any, ::Val{:namedarray}; start) at C:\Users\blake.riley\.julia\packages\CmdStan\t3xOP\src\utilities\convert_a3d.jl:50
  ...
Stacktrace:
 [1] #stan#4(::Type, ::Bool, ::Bool, ::String, ::Bool, ::Bool, ::Function, ::CmdStan.Stanmodel, ::Dict{String,Any}, ::String) at C:\Users\blake.riley\.julia\packages\CmdStan\t3xOP\src\main\stancode.jl:249
 [2] (::getfield(CmdStan, Symbol("#kw##stan")))(::NamedTuple{(:summary,),Tuple{Bool}}, ::typeof(CmdStan.stan), ::CmdStan.Stanmodel, ::Dict{String,Any}, ::String) at .\none:0 (repeats 2 times)
 [3] estimate_stan_model(::Int64, ::Int64, ::Int64, ::Int64, ::String) at C:\Users\blake.riley\.julia\packages\TestPkg\VWzbs\src\TestPkg.jl:28
 [4] top-level scope at none:0
```
The immediate cause is that CmdStan.jl changed the signature of `convert_a3d()` between v5.0.3 and the recent version, and StanDataFrames hasn't updated to match. That's a minor bug for StanDataFrames. What make this seem like a Pkg bug though is that I had CmdStan added (and later pinned) at v5.0.3 which has the old signature. Despite that, code from the later version is apparently being called. I'm suspicious I've had similar issues before where versions added to the global environment seemed to leak into what's being called by the package.

Below is a minimal example using Julia 1.1.1. I renamed my `.julia` folder to start from a fresh global environment, created a new package "TestPkg" with the following source file and Project.toml, and added the package (and nothing else) to the global environment. When calling `res = TestPkg.estimate_stan_model(100, "C:/home/code")`, I got the error above

TestPkg.jl
```julia
module TestPkg

using CmdStan
using StanDataFrames

function estimate_stan_model(n, pdir = pwd())
    bernoullimodel = """
    data { 
      int<lower=0> N; 
      int<lower=0,upper=1> y[N];
    } 
    parameters {
      real<lower=0,upper=1> theta;
    } 
    model {
      theta ~ beta(1,1);
      for (n in 1:N) 
        y[n] ~ bernoulli(theta);
    }
    """  
    inputdict = Dict("N" => n, "y" => [x > .5 ? 1 : 0 for x in rand(n)])
    
    stanmodel = Stanmodel(name = "BernoulliModel", model = bernoullimodel, 
        nchains = 2, num_samples = 100, num_warmup = 150,
        pdir = pdir, output_format = :dataframe)

    stan(stanmodel, inputdict, summary = false)
end

end
```

Project.toml
```toml
name = "TestPkg"
uuid = "48452700-8d37-11e9-0ca5-25f0afa87d29"
authors = ["blake.riley "]
version = "0.1.0"

[deps]
CmdStan = "593b3428-ca2f-500c-ae53-031589ec8ddd"
StanDataFrames = "80e77ffc-c35e-544b-8e57-5accc6d0de25"
```

Entry in Manifest.toml
```toml
....

[[CmdStan]]
deps = ["BinDeps", "DataFrames", "DelimitedFiles", "Documenter", "Homebrew", "MCMCChains", "Missings", "NamedArrays", "Pkg", "Reexport", "Statistics", "StatsPlots", "Test", "Unicode"]
git-tree-sha1 = "c610be2cff9ab26ec44cdb9c48587993233776c7"
pinned = true
uuid = "593b3428-ca2f-500c-ae53-031589ec8ddd"
version = "5.0.3"

....
```

**Comment by blakeriley** [comment]
Ah... I think I realized the issue. I assumed the package manifest would apply, but I should have specified compatibility in Project.toml. 

```toml
[compat]
CmdStan = "<= 5.0.3"
```

This could be clarified in the "Adding dependencies to the project" section of "Creating packages" in the Pkg docs, saying adding specific versions isn't sufficient and linking to "Compatibility"
