### ISSUE TITLE
Package Spec Idea

### ISSUE THREAD

**Issue by mileslucas** [JuliaLang/Pkg.jl#1342]
Hi, I have some ideas for what I'd like to see incorporated into Pkg `project.toml`, especially regarding compatibilies. Most of these ideas stem from [python's poetry](https://poetry.eustace.io/) packaging ideas.

In poetry (which uses a `.toml` file for configuration) there are some nice ways of listing dependencies

### 1. Normal Dependency with semvar:
```toml
[dependencies]
Unitful = { "^0.16", uuid="1986cc42-f94f-5a68-af5c-568840ba703d" }
```
This is great because it keeps the all the information about the dependency in one location, instead of split between the `dependencies` and `compat` sections.

### 2. Github dependency
```toml
[dependencies]
FastConv = { 
    git="https://github.com/aamini/FastConv.jl", 
    branch="master", 
    uuid="d7899f00-a588-5e12-9855-37624a64ff9a" 
}
```

### 3. Local dependency
```toml
[dependencies]
P_equals_NP_solution = { 
   path = "~/dev/P_equals_NP_solution",
   uuid="d7899f00-a588-5e12-9855-37624a64ff9a"
}
```

### 4. Multiple versions
```toml
[dependencies]
Unitful =[
   { "^0.16", uuid="1986cc42-f94f-5a68-af5c-568840ba703d" },
   { git="https://github.com/painterqubits/Unitful.jl", uuid="1986cc42-f94f-5a68-af5c-568840ba703d" },
]
```
----
I'm not familiar with how Pkg.jl actually works, but I definitely care about the packaging ecosystem. One of the largest problems I have with Python is its packaging nightmare. I'd be open to helping implement some of these issues but I'm not certain how successful I would be. Any discussion is also welcome!

**Comment by mileslucas** [comment]
For an alternative, we could list dependenices like this, too-
```toml
[[deps]]
name="Unitful"
version="0.16.0"
uuid="1986cc42-f94f-5a68-af5c-568840ba703d"

[[deps]]
name="FastConv"
version="0.3.0"
uuid="d7899f00-a588-5e12-9855-37624a64ff9a"
git="https://github.com/aamini/FastConv.jl"
branch="master"
```

which may lead to longer `project.toml` files but I think has potential to be much more readable/interpretable than the inline-tables method above.
