### ISSUE TITLE
Load all of my package's dependencies into the test environment

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#1503]
Would be fixed by #1233 

—-

Suppose that you have a package `Foo`. And suppose that the contents of `Foo.jl/Project.toml` are:
```toml
name = "Foo"
uuid = "..."
version = "1.0.0"

[deps]
PkgA = "..."
PkgB = "..."
PkgC = "..."

[compat]
PkgA = "1"
PkgB = "2"
PkgC = "3"
julia = "1"
```

And suppose that the contents of `Foo.jl/test/Project.toml` are:
```toml
[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

On Julia 1.2 and higher, when I do `Pkg.test("Foo")`, the dependencies `PkgA`, `PkgB`, and `PkgC` are not available in the test environment. I think that this is good behavior by default.

But sometimes, I need to override the default behavior and use the dependencies inside the test environment.

Obviously I can manually add all `PkgA`, `PkgB`, and `PkgC` to `Foo.jl/test/Project.toml`. But this can get quite inconvenient when I have a lot of dependencies.

Is there an easy way that I can load all of the dependencies of `Foo` into the test environment with a single command?
