### ISSUE TITLE
Refer to binary files in package directory as artifact for relocatable apps

### ISSUE THREAD

**Issue by sdewaele** [JuliaLang/Pkg.jl#1743]
Applications and packages frequently depend on (small) binary files. For example, [XLSX.jl](https://github.com/felipenoris/XLSX.jl) uses template Excel files. Other applications may include a small dataset, a logo image, etc. These can conveniently be maintained in the package repository. However, currently the only easy method to use these is to refer to them using `@__DIR__` , see [here](https://github.com/felipenoris/XLSX.jl/blob/48e6c47ecdc43e63f0f487c324dfac0e418b5eee/src/write.jl#L11) for an example in XLSX.jl. This issue is that this breaks [relocatability](https://julialang.github.io/PackageCompiler.jl/dev/apps/#Apps-1).

Would it be possible to expand the artifact mechanism to refer to binary files as an artifact, thus eliminating the need to use `@__DIR__`? Please note that the location of the file is not of interest in this case, only the content of the file. Besides eliminating the usage of `@__DIR__`, a further benefit is that PackageCompiler will automatically include the file into the executable.

Hosting files like these in a web server is not very attractive IMO, because (i) it requires a package developer to find a hosting server, just for that small excel template file (ii) this cannot be versioned along with the code in the repo.

Perhaps the entry in the artifact file could be something like this:
```toml
[blank_xlsx]
git-tree-sha1 = "43563e7631a7eafae1f9f8d9d332e3de44ad7239"

    [[blank_xlsx.get]]
    relpath = "data/blank.xlsx"
    sha256 = "e65d2f13f2085f2c279830e863292312a72930fee5ba3c792b14c33ce5c5cc58"
```
I am not at all an expert in artifact files, so this can probably be improved! I hope that including this is easier than supporting libraries, which need to be built separately for different target platforms.

See also https://github.com/felipenoris/XLSX.jl/issues/127.
