### ISSUE TITLE
Expand artifact selection beyond Platform/CompilerABI

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#1780]
In the future, Artifacts are most likely going to need to be split by more than just the `Platform`/`CompilerABI` buckets that we have so far been using.  We may have artifacts compiled for different chip ISAs (e.g. a numerical library with `avx512` support), with alternative backend supports (e.g. a library that has `cuda` support turned on) or other such variants.

In all these cases, it seems clear to me that the common theme is "matching an artifact to the current environment", whether that environment be the OS, the CPU's capabilities, the currently-mandated `libgfortran` version, or the presence of CUDA libraries.  While we could increase the number of tags that a `Platform` has and solve the problem that way, I personally don't really like that, and would rather create an extensible method by which users can provide code that runs at compile-time, inspects the system, and provides tags that are then matched against the tags recorded in the `Artifacts.toml` file.

As an example, here's two `Artifacts.toml` entries from `libLLVM_jll.jl`:

```toml
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf5710efc0f8c4e00073e832944064380390f7fc"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "175d249b0178c4504d9337750f47c76249d16982810127f7507cbf3db53d6001"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v8.0.1+0/libLLVM.v8.0.1.aarch64-linux-musl-cxx11.tar.gz"

[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "955bb29cfbde1b21698c84b67d85a2e1f8e1a6f3"
os = "windows"

    [[libLLVM.download]]
    sha256 = "6a380dd4d4fde4f1b42c6518d64dbf8461544d32f3bb7c2ed5fbec7a5e800f31"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v8.0.1+0/libLLVM.v8.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
```

At install and compile time, all mentions of the `libLLVM` artifact, (whether it be within `Pkg.add()` or in the user's code via `artifact"libLLVM"`) will pass through [`select_platform()`](https://github.com/JuliaLang/Pkg.jl/blob/89792a8a00c619aa5e76798083fda9d80212a07b/src/BinaryPlatforms.jl#L780-L796).  This function, which is currently very tightly integrated with the `Platform` and `CompilerABI` types, takes in a dictionary mapping (which is what that TOML file above defines) and selects the key that "best matches" the current platform's `Platform` object.

I propose that users be able to add arbitrary tags to their `Artifacts.toml` files.  Things like `cuda_capability = "3"`, or `cpu_isa = "avx"`, etc...  This would couple with a mechanism for the user to provide code that `Pkg` would source, in order to determine the currently-running system's tags.  I'm not sure what the best way to do that would be, here are some options:

* Pkg could check a "blessed" location for this, perhaps `src/pkg_ext/PlatformHooks.jl`, wherein the user would define a `annotate_platform(p::Platform)` function, which is allowed to introspect and determine things about the current system.
* The `Artifacts.toml` file itself could include a field with inline code.  Ugly, but eminently portable.
* We could write a `PkgExt.jl` package that monkey-patches `Pkg` upon being loaded, then any package that relies upon this functionality must depend on that package first.  (this doesn't quite work if you need to extend `Pkg` just to install your package outright; the ordering doesn't quite work out there)

I'm open to suggestions for better ways to implement this, or even for someone to change my mind about the best way to deal with this.  But I think as things like CUDA get more and more popular, we're going to have an explosion of `LibFoo_jll` and `LibFooCUDA_jll`.  Note that this starts getting very close to the "variants" debate, but I'd like to keep this feature clear of that by stating that the introspection done by this feature should not depend on what packages are installed, but rather the characteristics of the hardware itself; it should be as idempotent as possible.
