### ISSUE TITLE
Requiring the [package] section in Project.toml of packages

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/Pkg.jl#179]
Current Project.toml of a package starts without any table header:
```toml
name = "Example"
uuid = "..."
license = "MIT"
# ...
```

That's fine for now but I think Project.toml will be used not only for packages but also for general non-package projects. In such cases, it is more explicit to require the `[package]` section header as Rust's Cargo.toml does:
```toml
[package]
name = "Example"
uuid = "..."
license = "MIT"
# ...
```

I think it is useful to distinguish package projects from others so that Julia can do something special when it finds a package (I don't come up with any concrete ideas, but I groundlessly believe it will be needed in the future).
