### ISSUE TITLE
Incorrect path resolving:  expected package to exist at path `D:\C:\Users\adria\.julia\dev\Stipple`

### ISSUE THREAD

**Issue by essenciary** [JuliaLang/Pkg.jl#1796]
The issue occurs when we have the following setup: 
1 - packages are dev-ed into C:\Users\adria\.julia\dev
2 - package A is dev-ed
3 - package B is dev-ed and has A as a dependency
4 - project P devs package B as dependency
5 - project P is on drive D

In project P:
```julia
(german_credit_dashboard) pkg> dev StippleQuasar
Path `C:\Users\adria\.julia\dev\StippleQuasar` exists and looks like the correct package. Using existing path.
  Resolving package versions...
ERROR: expected package `Stipple [c3245d6e]` to exist at path `D:\C:\Users\adria\.julia\dev\Stipple`
```
In B: 
```julia
(StippleQuasar) pkg> st
Project StippleQuasar v0.1.0
Status `C:\Users\adria\.julia\dev\StippleQuasar\Project.toml`
  [c3245d6e] Stipple v0.1.0 [`C:\Users\adria\.julia\dev\Stipple`]
```

Relefant part of Manifest file of `StippleQuasar`: 
```toml
[[Stipple]]
deps = ["CSV", "DataFrames", "FilePaths", "Genie", "JSON", "Logging", "Observables", "Reexport", "Revise", "Tables"]
path = "C:\\Users\\adria\\.julia\\dev\\Stipple"
uuid = "c3245d6e-4e41-4672-accb-64620d5e5a71"
version = "0.1.0"
```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto
