### ISSUE TITLE
git-tree-sha1 for Windows and Linus are different for artifacts with completely same contents.

### ISSUE THREAD

**Issue by racinmat** [JuliaLang/Pkg.jl#1914]
Artifacts.toml uses `git-tree-sha1` for artifacts, which is different for Windows and Linux even for the same tarball.
Is this intentional or not?
E.g. on windows this is working:
`Artifacts.toml` with contents:
```toml
[tzdata_2016j]
git-tree-sha1 = "cae342ed5640427089e8d00f7cb4a235aa6a3738"
lazy = true

    [[tzdata_2016j.download]]
    sha256 = "f5ee4e0f115f6c2faee1c4b16193a97338cbd1b503f2cea6c5a768c82ff39dc8"
    url = "https://data.iana.org/time-zones/releases/tzdata2016j.tar.gz"
```

following code
```julia
using SHA
using Base: SHA1
using Pkg
using Pkg.GitTools
using Pkg.Artifacts
Pkg.activate(".")
@info SHA1(Pkg.GitTools.tree_hash(artifact"tzdata_2016j"))
```
produces
```julia
[ Info: cae342ed5640427089e8d00f7cb4a235aa6a3738
```
on windows, but 
```julia
Downloading artifact: tzdata_2016j
######################################################################## 100.0%
┌ Error: Tree Hash Mismatch!
│   Expected git-tree-sha1:   cae342ed5640427089e8d00f7cb4a235aa6a3738
│   Calculated git-tree-sha1: d07b6f4c96583b520c598c2ec642997456bc7a31
ERROR: LoadError: Unable to automatically install 'tzdata_2016j' from '/root/Artifacts.toml'
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] ensure_artifact_installed(::String, ::Dict{String,Any}, ::String; platform::Pkg.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Artifacts.jl:894
 [3] do_artifact_str(::String, ::Dict{String,Any}, ::String, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Artifacts.jl:1023
 [4] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./essentials.jl:712
 [5] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:711
 [6] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Artifacts.jl:1058
 [7] include(::Module, ::String) at ./Base.jl:377
 [8] exec_options(::Base.JLOptions) at ./client.jl:288
 [9] _start() at ./client.jl:484
in expression starting at /root/script.jl:7
```
on linux. 
Sha256 of each file in `~/.julia/artifacts/d07b6f4c96583b520c598c2ec642997456bc7a31` on linux and `~\.julia\artifacts\cae342ed5640427089e8d00f7cb4a235aa6a3738` windows is totally the same. Is this intended behavior or some bug?
