### ISSUE TITLE
proposal for package tags and descriptions in registry

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/Pkg.jl#1967]
I feel it could be nice to allow storing some description about the package itself in the registry, such as tags and a short description. This would make things more viable, I once proposed this on discourse as a reply, but I can't find the post anymore.

This proposal is partly inspired by PyPI's classifiers (https://www.python.org/dev/peps/pep-0301/#distutils-trove-classification).

TL;DR

I'm basically proposing two new fields `tags` and `description` in the `Package.toml` and `Project.toml`, a typical new `Package.toml` would look like the following

```toml
name = "Yao"
uuid = "5872b779-8223-5990-8dd0-5abbb0748c8c"
repo = "https://github.com/QuantumBFS/Yao.jl.git"
tags=[
  "physics",
  "quantum",
]
description="Extensible, Efficient Quantum Algorithm Design for Humans."
```

The corresponding `Project.toml` can be 

```toml
name = "Yao"
uuid = "5872b779-8223-5990-8dd0-5abbb0748c8c"
version = "0.6.3"
tags=[
  "physics",
  "quantum",
]
description="Extensible, Efficient Quantum Algorithm Design for Humans."


[deps]
...
```

### Tags

Tags are categories that a package belongs, I think at least in principle, available tags it should be managed by registry owners to make sure there are not too many close meaning tags (e.g "quantum" and "quantum-physics" etc.) they can be generated automatically from GitHub tags as well (but one might want to filter out some tags or redirect them to make things less duplicate).

A package can belong to multiple category and categories in the registry don't have to contain hierarchy, but a frontend to the registry may provide such hierarchy, e.g quantum category can be inside `physics` category: `physics/quantum`. This is a major difference comparing to PyPI's classifiers.

### Description

The description should be a short sentence that briefly describes what does the package do and what feature it contains. I think also up to the registry owner, they can limit the total length of this description (e.g 120 characters) to make sure it's simple and brief to read for the user. 

**Why can't I just read them from GitHub?**

1. Reading a single package from GitHub is actually fine, but if we want to allow someone to search a package with description, we need to actually store things. e.g with this new feature, this will allow people to do some simple search on packages directly from their REPL/terminal/IDE without sending request to GitHub. Given currently without authentication, GitHub only allows 50 requests per day. I implemented this feature as an example in [IonCLI](https://github.com/Roger-luo/IonCLI.jl) (but now it has to send a request to GitHub for every search result):

![image](https://user-images.githubusercontent.com/8445510/90553469-6c67ad80-e162-11ea-952e-dbf16723dd14.png)

2. packages may not be hosted on GitHub, if the project is hosted on somewhere else that do not provide a github-like tag and description service, then one cannot search it in this way at all, and it can be quite common that one do not remember what exactly the package name is, but a quite vague name want to search.

3. This feature will allow one to search behind a firewall with only a package server available if GitHub is not fully accessible.
