### ISSUE TITLE
Dependency on a privately registered package

### ISSUE THREAD

**Issue by wildart** [JuliaLang/Pkg.jl#2385]
I want to narrow the scope of #492 to the following problem: Is it possible to add a package dependency into the project where the dependency is **registered** in a private registry?

Currently, a private registry need to be added manually to the Pkg configuration, prior installing any package registered in such registry. Can this process be automated? Sure, if all dependent registries are added to the project file.

The project file could have an optional `[registries]` section that would specify list of additional registry repositories required to be added to local configuration before installing any dependencies listed in the `[deps]` section.

```toml
name = "Foo"
uuid = "4bdd1c6b-68bb-4dfe-a423-fa0d59eb7384"
version = "0.1.0"

[deps]
Bar = "ce02910b-3083-40c5-958c-8fd1036218f1"

[registries]
PrivateRegistry = "https://www.bar.com/PrivateRegistry.git"
```
EDIT: It appears I messed the terminology up, thus some corrections.
