### ISSUE TITLE
Removing a dependency (sometimes?) removes test-dependency compat

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/Pkg.jl#2419]
I've seen this several times but generally in complicated and/or private code, but I was pretty quickly able to reproduce it here too: https://github.com/ericphanson/TestPkg.jl.

TLDR: I have a project like
```toml
name = "TestPkg"
uuid = "37f6bc05-9e90-43d5-90c6-4d69d7097606"
authors = ["Eric Hanson <5846501+ericphanson@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
Aqua = "0.5"
DataFrames = "0.22"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[targets]
test = ["Aqua"]
```
and if I remove `DataFrames` then the whole compat section goes away. I've seen this also when there were more dependencies and more compat; then the Aqua compat goes away but the section stays.

Julia 1.5.3 and 1.6 rc1 on MacOS (though I've seen it on various linuxes and I think on Windows with WSL2 as well).
