### ISSUE TITLE
Pkg puts in wrong dependencies for versioned stdlibs 

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#2698]
If you start a new environment and add `p7zip_jll` you get an entry in the manifest:

```toml
[[deps.p7zip_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
version = "16.2.1+1"
```

But the `p7zip_jll`  does not depend on Pkg: https://github.com/JuliaLang/julia/blob/master/stdlib/p7zip_jll/Project.toml.

What seems to happen is that this check:

https://github.com/JuliaLang/Pkg.jl/blob/b1ec6de5417da990a75c186a24f88fb801657d12/src/Operations.jl#L416

fails and then Pkg goes and looks in the registry for compat info for the package.

cc @staticfloat since I am quite sure this got introduced in https://github.com/JuliaLang/Pkg.jl/pull/2614 with the extra `stdlib_version === nothing` check added.
