### ISSUE TITLE
Artifact doesn't get installed on Julia 1.7.1

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaLang/Pkg.jl#2979]
From a [Discourse post](https://discourse.julialang.org/t/julia-artifact-was-not-installed-correctly/76038). When adding some Artifact such as 

```toml
[MathJax]
git-tree-sha1 = "74d0a953af18dcd657e42a5cd95e77d791882528"

    [[MathJax.download]]
    sha256 = "ba979bd15d82065aebea460ed77e4b3fe217ca3a7876cc69606147b85d8fb3ce"
    url = "https://github.com/mathjax/MathJax/archive/refs/tags/3.2.0.tar.gz"
```

`instantiate` doesn't always work. That is, `instantiate` doesn't install the Artifact.

```julia
pkg> instantiate

julia> artifact"MathJax"
ERROR: Artifact "MathJax" was not installed correctly. Try `using Pkg; Pkg.instantiate()` to re-install all missing resources.
```

In this case, I am on Julia 1.7.1 and I think that I've had this Artifact installed before. However, I've made some arbitrary changes to the SHA in the hope to trigger something, but that didn't work. When switching to Julia 1.6, the I correctly see that the system is downloading the artifact (and giving a hash mismatch error as expected).

So, it is likely that this is a regression since 1.6.5, but I am not 100 % sure. Apologies for not being able to provide an easier strategy to reproduce

EDIT: Could it be that the error is the problem and that `pkg> up` should be used instead?
