### ISSUE TITLE
Convenience syntax for adding package with extensions

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/Pkg.jl#3288]
I'm looking forward to the introduction of extensions, and it occurs to me that it in a situation like this:
```toml
name = "MyPkg"

[weakdeps]
# ...

[extensions]
Ext = ["PkgA", "PkgB"]
```

It could be nice to be able to say you want to add `MyPkg` and ensure that `Ext` will be available, which has me thinking it might be nice to be able to do say `pkg> add MyPkg+Ext` to make this happen (i.e. add `MyPkg` and relevant weakdeps).

How does this sound?
