### ISSUE TITLE
Overly restricting package versions by julia compatibility requirements

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/Pkg.jl#354]
When I run `Pkg.add("OffsetArrays")` with no other packages installed on my current master build of Julia (`v"0.7.0-alpha.43"`), I get a much older version of OffsetArrays than I expected (got: v"0.2.12", expected v"0.5.0").  Checking the graph's logs shows that propagating constraints:

```
restricted by julia compatibility requirements to versions: [0.2.4, 0.2.12] or uninstalled, leaving only versions: [0.2.4, 0.2.12]
```

This is unexpected, as the current Compat.toml is quite simple for OffsetArrays; no versions should be restricted by Julia compatibility requirements:

```toml
["0.1"]
julia = "0.3-0.7"

["0.2-0.3"]
julia = "0.5-0.7"

["0.2.14-0.4.0"]
Compat = "0.19-0.68"

["0.4-0.5"]
julia = "0.6-0.7"

["0.4.1-0.4.2"]
Compat = "0.32-0.68"

["0.5"]
Compat = "0.45-0.68"
```

This is the same install that has seen similar odd resolver issues (#303) — perhaps also related to erroneously applying Julia constraints?
