### ISSUE TITLE
Allow comments in `[compat]` entries

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/Pkg.jl#3686]
Ensuring that the `[compat]` version bounds for a package are correct can be tedious, and often requires experience and historic knowledge. It is thus important to be able to document why a particular compat entry is there.

I am thinking of comments along these lines: "version x.y.z doesn't work, try again after the next minor release", or "this breaks on BSD", or "doesn't handle snarfblurbs larger than 2 GByte", etc. This allows maintainers to codify their knowledge about version bounds, what was tried in the past, what the symptoms were, whether it is worthwhile to relax a version bound, etc.

It would be convenient to have these comments in the `[compat]` section, attaches to a particular version bound. Just spinning yarn – maybe such a syntax might work?
```toml
Dependency = "<1.2.3   # function `flexdup` was accidentally removed in 1.2.3"
Misery = "=4.5.5   # keep this fixed, Misery doesn't use semver"
Chirp1 = "0.1, 0.2, 0.3   # 0.4 doesn't work, try 0.5 next"
Chirp2 = "0.1, 0.2, 0.3   # try 0.4 once it's available"
```
