### ISSUE TITLE
Bad resolve if different build metadata versions have different dependencies

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/Pkg.jl#3795]
Not 100% clear I understand everything here, but it looks like a bug to me:

Consider the following (valid) Manifest (+all the deps; full MWE environment [in this gist](https://gist.github.com/mortenpi/ecf9de3c00c59f344f039887df9f9b02); can almost be recreated with `pkg> add Wayland_jll#Wayland-v1.21.0+0`):

```toml
[[deps.Wayland_jll]]
deps = ["Artifacts", "Expat_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "ed8d92d9774b077c53e1da50fd81a36af3744c1c"
uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
version = "1.21.0+0"
```

when resolving this manifest (including on `1.11.0-DEV.1593 (2024-02-14)`), you end up with this diff:

```diff
+[[deps.EpollShim_jll]]
+deps = ["Artifacts", "JLLWrappers", "Libdl"]
+git-tree-sha1 = "8e9441ee83492030ace98f9789a654a6d0b1f643"
+uuid = "2702e6a9-849d-5ed8-8c21-79e8b8f9ee43"
+version = "0.0.20230411+0"
+

 [[deps.Wayland_jll]]
-deps = ["Artifacts", "Expat_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg", "XML2_jll"]
+deps = ["Artifacts", "EpollShim_jll", "Expat_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg", "XML2_jll"]
 git-tree-sha1 = "ed8d92d9774b077c53e1da50fd81a36af3744c1c"
 uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
 version = "1.21.0+0"
```

The `Wayland_jll` version does not get updated, but `EpollShim_jll` gets added as a new dependency, leading to an invalid manifest. This is because [Wayland_jll added EpollShim_jll as a dependency when going from `1.21.0+0` -> `1.21.0+1`](https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/commit/3f61b6046748dc6a94b706498a8dea48a34daeca#diff-72ed386c2a0cd1d23c0968297e70023ed98c22490d146dd89fc91f48369bad4d).

Not really sure whose "fault" it is here, but it feels like Pkg should not generate invalid manifests, even if there's the build metadata magic happening. Instead, it should either update the version or don't update dependency list.

X-ref: https://github.com/JuliaLang/Pkg.jl/issues/1568
