### ISSUE TITLE
Specifying registries needed for a project in the Project file

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#3845]
From https://github.com/JuliaLang/Pkg.jl/pull/3783#issuecomment-1974794079

> Could it make sense to be able to specify a registry in the sources block? Maybe with a separate registries block to have the url. That way a Project/Manifest does not need to depend on the registries already being installed.

`[sources]` made it easier to resolve a manifest with unregistered dependencies without having to manually add these dependencies by URL. However, you still need to make sure that the registries are available. So the next step would be to store the set of registries needed in the project file as well so that they are automatically installed for you.

This issue is about how to specify that information in the project file.

The first question is if we need to store the UUID of the registry somewhere. It's kind of silly since there are so few registries. If we then only look at the registry name we could have:

```toml
[registries]
CustomRegistry = "https://my.custom.registry/CustomRegistry"
...
```

or maybe this should be a dict and be

```toml
[registries]
CustomRegistry = {url = "https://my.custom.registry/CustomRegistry"}
...
```

------

Should custom registries be auto-added to the project file once a package is added to the project that is not available in general?

---------
cc @ericphanson, @Seelengrab
