### ISSUE TITLE
sources section of Project.toml does not support subdir

### ISSUE THREAD

**Issue by piever** [JuliaLang/Pkg.jl#4026]
As discussed in Slack, attempting to specify a non-top-level package in a GitHub repo in the `sources` section of Project.toml errors.

MWE:

```toml
[deps]
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"

[sources]
DuckDB = {url = "https://github.com/duckdb/duckdb", subdir = "tools/juliapkg", rev = "main"}
```

Calling `Pkg.resolve()` on the above project fails with

```
ERROR: Invalid key `subdir` in `source` section
```

For reference, DuckDB is a monorepo where the julia package is in the `tools/juliapkg` folder.

Version information (release candidate installed via juliaup):

```julia-repl
julia> versioninfo()
Julia Version 1.11.0-rc3
Commit 616e45539db (2024-08-26 15:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```
