### ISSUE TITLE
`rev` in `[sources]` is ignored unless there's also the `url` specification

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Pkg.jl#4165]
Instantiate the following environment:
```toml
[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"

[sources]
Example = {rev = "ba3d6704f09330ae973773496a4212f85e0ffe45"}
```
You get
```
(tmp) pkg> st
Status `/tmp/Project.toml`
  [7876af07] Example v0.5.5
```
The `rev` specification is completely ignored, unless you have also the `url`:
```toml
[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"

[sources]
Example = {url = "https://github.com/JuliaLang/Example.jl", rev = "ba3d6704f09330ae973773496a4212f85e0ffe45"}
```
Note: this is ***not*** related to #4157, it can be replicated in a clean system without modifying a Project file in an already resolved environment, resolving/instantiating the fresh environment just ignores the lone `rev`.

```julia-repl
julia> versioninfo()
Julia Version 1.13.0-DEV.96
Commit 3c02af98dca (2025-02-21 00:36 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 22 × Intel(R) Core(TM) Ultra 7 155H
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, alderlake)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 22 virtual cores)
```
