### ISSUE TITLE
Extension dependencies as weak dependencies

### ISSUE THREAD

**Issue by Zetison** [JuliaLang/Pkg.jl#4175]
If extensions have dependencies not present in the main project they must either be listed in `[deps]` or can be included in the extension i.e. (with `EMGExt` being an extension with `EnergyModelsGeography`)
```toml
[extensions]
EMGExt = ["GeoJSON", "GeoMakie", "HTTP", "EnergyModelsGeography"]
```
The former would require redundant dependencies (if EMGExt is not used) while the latter would in order to use the extension require not only `EnergyModelsGeography` to be loaded, but `GeoJSON`, `GeoMakie`, and `HTTP` as well. It would be convenient if these three packages would be loaded only when EnergyModelsGeography is loaded. Could this be implemented?
