### ISSUE TITLE
[sources] fails to pull remote deps when nested

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/Pkg.jl#4197]
So if you have "nested" local deps like this (full MWE here: https://github.com/mortenpi/pkg-4197-mwe):

```toml
name = "PackageA"
uuid = "bbcb243f-f034-2038-cf56-a1fff5ae3881"
authors = ["JuliaHub Inc"]
version = "0.0.0"

[deps]
PackageB = "35109ab6-39ae-8b6d-e3b4-cc633fdcfb67"

[sources]
PackageB = { path = "../PackageB" }
```

```toml
name = "PackageB"
uuid = "35109ab6-39ae-8b6d-e3b4-cc633fdcfb67"
authors = ["JuliaHub Inc"]
version = "0.0.0"

[deps]
PackageC = "b160dae6-bb54-ebdb-3ad7-d2b4dbb778f3"
ReturnScope = "3caac13a-2753-4d5a-becf-3271e52727bc"

[sources]
PackageC = { path = "../PackageC" }
ReturnScope = { url = "https://github.com/mortenpi/ReturnScope.jl" }
```

Pkg correctly figures out where to find `PackageC`, but not how to pull `ReturnScope` (i.e. any remote dep provided via `url`). If you comment out `ReturnScope` it works the following works as expected:

```
$ julia +nightly --project=PackageA/ -e 'using Pkg; Pkg.instantiate()'
    Updating registry at `~/.julia/registries/General.toml`
ERROR: Unsatisfiable requirements detected for package ReturnScope [3caac13a]:
 ReturnScope [3caac13a] log:
 ├─ReturnScope [3caac13a] has no known versions!
 └─restricted to versions * by PackageB [35109ab6] — no versions left
   └─PackageB [35109ab6] log:
     ├─possible versions are: 0.0.0 or uninstalled
     ├─restricted to versions * by PackageA [bbcb243f], leaving only versions: 0.0.0
     │ └─PackageA [bbcb243f] log:
     │   ├─possible versions are: 0.0.0 or uninstalled
     │   └─PackageA [bbcb243f] is fixed to version 0.0.0
     └─PackageB [35109ab6] is fixed to version 0.0.0
Stacktrace:
  [1] check_constraints(graph::Pkg.Resolve.Graph)
    @ Pkg.Resolve ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/Resolve/graphtype.jl:1046
  [2] Pkg.Resolve.Graph(compat::Dict{Base.UUID, Dict{VersionNumber, Dict{Base.UUID, Pkg.Versions.VersionSpec}}}, compat_weak::Dict{Base.UUID, Dict{VersionNumber, Set{Base.UUID}}}, uuid_to_name::Dict{Base.UUID, String}, reqs::Dict{Base.UUID, Pkg.Versions.VersionSpec}, fixed::Dict{Base.UUID, Pkg.Resolve.Fixed}, verbose::Bool, julia_version::VersionNumber)
    @ Pkg.Resolve ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/Resolve/graphtype.jl:350
  [3] deps_graph(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, uuid_to_name::Dict{Base.UUID, String}, reqs::Dict{Base.UUID, Pkg.Versions.VersionSpec}, fixed::Dict{Base.UUID, Pkg.Resolve.Fixed}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/Operations.jl:698
  [4] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{PackageSpec}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/Operations.jl:522
  [5] up(ctx::Pkg.Types.Context, pkgs::Vector{PackageSpec}, level::UpgradeLevel; skip_writing_project::Bool, preserve::Nothing)
    @ Pkg.Operations ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/Operations.jl:1890
  [6] up
    @ ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/Operations.jl:1869 [inlined]
  [7] up(ctx::Pkg.Types.Context, pkgs::Vector{PackageSpec}; level::UpgradeLevel, mode::PackageMode, preserve::Nothing, update_registry::Bool, skip_writing_project::Bool, kwargs::@Kwargs{})
    @ Pkg.API ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/API.jl:393
  [8] up
    @ ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/API.jl:367 [inlined]
  [9] up
    @ ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/API.jl:169 [inlined]
 [10] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, workspace::Bool, julia_version_strict::Bool, kwargs::@Kwargs{})
    @ Pkg.API ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/API.jl:1202
 [11] instantiate
    @ ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/API.jl:1177 [inlined]
 [12] instantiate(; kwargs::@Kwargs{})
    @ Pkg.API ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/API.jl:1176
 [13] top-level scope
    @ none:1
 [14] eval(m::Module, e::Any)
    @ Core ./boot.jl:489
 [15] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:294
 [16] _start()
    @ Base ./client.jl:560
```

Version (but also present on 1.11):

```
julia> versioninfo()
Julia Version 1.13.0-DEV.315
Commit d9441ac9bc0 (2025-03-27 18:29 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 12th Gen Intel(R) Core(TM) i7-1260P
  WORD_SIZE: 64
  LLVM: libLLVM-19.1.7 (ORCJIT, alderlake)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 16 virtual cores)
```
