### ISSUE TITLE
`dev https://...` fails with confusing error message

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaLang/Pkg.jl#4213]
```
(Foobar) pkg> dev https://github.com/JuliaLang/Example.jl
     Cloning git-repo `https://github.com/JuliaLang/Example.jl`
Path `/Users/nickr/.julia/dev/Example` exists and looks like the correct repo. Using existing path.
ERROR: `path` and `url` are conflicting specifications
```

I'm guessing this is somehow because the `Project.toml` has a `sources` section?
It looks to me like i gave a url, then it says a path and errors because... something about a path?
i'm not saying behaviour is wrong, just the message is confusing to me... and leave me without an idea of what my next step should be.

Seen on Julia v1.11 and nightly (1.13.0-DEV)

`Project.toml` looks like:
```toml
name = "Foobar"
uuid = "469444d5-79b5-4f80-a9af-0769fa2f9410"
authors = [""]
version = "0.1.0"

[preferences.Foobar]
QUX3 = false

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
LocalPkg = "fcf55292-0d03-4e8a-9e0b-701580031fc3"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[sources]
Example = {url = "https://github.com/JuliaLang/Example.jl"}
LocalPkg = {path = "LocalPkg"}
```
And the `Manifest.toml` contains
```
[[deps.Example]]
git-tree-sha1 = "84ec67045e0af90908e775e4d7a3782b9f27e98a"
repo-url = "https://github.com/JuliaLang/Example.jl"
uuid = "7876af07-990d-54b4-ab0e-23690620f79a"
version = "0.5.5"
```
