### ISSUE TITLE
[workspace] Issue updating sub-project without an existing Manifest.toml

### ISSUE THREAD

**Issue by nhz2** [JuliaLang/Pkg.jl#4222]
I am using the new workspace feature in the https://github.com/JuliaIO/ChunkCodecs.jl monorepo.

If I clone the repo, which has no `Manifest.toml`, and update a sub-project, the dependencies are from the registry and not the local versions.

`ChunkCodecCore` and `LibZlib` are both sub-projects of the top workspace, and `LibZlib` depends on `ChunkCodecCore`.

For example, after:

```sh
julia --project=LibZlib -e 'import Pkg; Pkg.update()'
```

The `deps.ChunkCodecCore` section in `Manifest.toml` contains:

```toml
[[deps.ChunkCodecCore]]
git-tree-sha1 = "83cc01ac207dde8e10d08c3b1d8bd994c5c0c25e"
uuid = "0b6fb165-00bc-4d37-ab8b-79f91016dbe1"
version = "0.4.2"
```

If instead I run:

```sh
julia --project=. -e 'import Pkg; Pkg.update()'
```

I get the expected:

```toml
[[deps.ChunkCodecCore]]
path = "ChunkCodecCore"
uuid = "0b6fb165-00bc-4d37-ab8b-79f91016dbe1"
version = "0.4.2"
```

```julia-repl
julia> versioninfo()
Julia Version 1.13.0-DEV.427
Commit ff0a9313de7 (2025-04-22 14:02 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
  WORD_SIZE: 64
  LLVM: libLLVM-19.1.7 (ORCJIT, skylake)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 16 virtual cores)
```
