### ISSUE TITLE
Confusing non-existent dependency error

### ISSUE THREAD

**Issue by omus** [JuliaLang/Pkg.jl#426]
Make a Project.toml file which includes:
```toml
[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "0.59"
```
Then run Julia 0.7-beta try to test the package and you'll get:
```
ERROR: LoadError: ArgumentError: Package Compat does not have IterativeEigensolvers in its dependencies:
 - If you have Compat checked out for development and have
   added IterativeEigensolvers as a dependency but haven't updated your primary
   environment's manifest file, try `Pkg.resolve()`.
 - Otherwise you may need to report an issue with Compat.
```
The error above is misleading as [Compat 0.59 does declare IterativeEigensolvers](https://github.com/JuliaLang/Compat.jl/blob/v0.59.0/Project.toml#L10) as a dependency but IterativeEigensolvers is no longer in the stdlib as of Julia 0.7-beta
