### ISSUE TITLE
Preserving comments in Project.toml

### ISSUE THREAD

**Issue by alyst** [JuliaLang/Pkg.jl#592]
Are Pkg.* operations supposed to preserve the comments in `Project.toml`? ATM (0.7.0-rc3) it looks like it's not the case.

The use case: I would like to take a note that the dependency is only required for benchmarking (so it should go to "[extras]" once we can specify custom target for code execution):
```toml
...
[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63" # move to extras once custom targets are supported
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CPUTime = "a9c8d775-2e2e-55fc-8582-045d282d599e" # move to extras once custom targets are supported
...
```
Also would be nice to preserve the comments in "[compat]" section.

Currently e.g. "]add CSV" removes it.
